/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DictationRouteImport } from './routes/dictation'
import { Route as VocabularyRouteRouteImport } from './routes/vocabulary/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VocabularyIndexRouteImport } from './routes/vocabulary/index'
import { Route as VocabularyWorksheetIdRouteImport } from './routes/vocabulary/$worksheetId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DictationRoute = DictationRouteImport.update({
  id: '/dictation',
  path: '/dictation',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyRouteRoute = VocabularyRouteRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyIndexRoute = VocabularyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VocabularyRouteRoute,
} as any)
const VocabularyWorksheetIdRoute = VocabularyWorksheetIdRouteImport.update({
  id: '/$worksheetId',
  path: '/$worksheetId',
  getParentRoute: () => VocabularyRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vocabulary': typeof VocabularyRouteRouteWithChildren
  '/dictation': typeof DictationRoute
  '/login': typeof LoginRoute
  '/vocabulary/$worksheetId': typeof VocabularyWorksheetIdRoute
  '/vocabulary/': typeof VocabularyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dictation': typeof DictationRoute
  '/login': typeof LoginRoute
  '/vocabulary/$worksheetId': typeof VocabularyWorksheetIdRoute
  '/vocabulary': typeof VocabularyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vocabulary': typeof VocabularyRouteRouteWithChildren
  '/dictation': typeof DictationRoute
  '/login': typeof LoginRoute
  '/vocabulary/$worksheetId': typeof VocabularyWorksheetIdRoute
  '/vocabulary/': typeof VocabularyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/vocabulary'
    | '/dictation'
    | '/login'
    | '/vocabulary/$worksheetId'
    | '/vocabulary/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dictation' | '/login' | '/vocabulary/$worksheetId' | '/vocabulary'
  id:
    | '__root__'
    | '/'
    | '/vocabulary'
    | '/dictation'
    | '/login'
    | '/vocabulary/$worksheetId'
    | '/vocabulary/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VocabularyRouteRoute: typeof VocabularyRouteRouteWithChildren
  DictationRoute: typeof DictationRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictation': {
      id: '/dictation'
      path: '/dictation'
      fullPath: '/dictation'
      preLoaderRoute: typeof DictationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary/': {
      id: '/vocabulary/'
      path: '/'
      fullPath: '/vocabulary/'
      preLoaderRoute: typeof VocabularyIndexRouteImport
      parentRoute: typeof VocabularyRouteRoute
    }
    '/vocabulary/$worksheetId': {
      id: '/vocabulary/$worksheetId'
      path: '/$worksheetId'
      fullPath: '/vocabulary/$worksheetId'
      preLoaderRoute: typeof VocabularyWorksheetIdRouteImport
      parentRoute: typeof VocabularyRouteRoute
    }
  }
}

interface VocabularyRouteRouteChildren {
  VocabularyWorksheetIdRoute: typeof VocabularyWorksheetIdRoute
  VocabularyIndexRoute: typeof VocabularyIndexRoute
}

const VocabularyRouteRouteChildren: VocabularyRouteRouteChildren = {
  VocabularyWorksheetIdRoute: VocabularyWorksheetIdRoute,
  VocabularyIndexRoute: VocabularyIndexRoute,
}

const VocabularyRouteRouteWithChildren = VocabularyRouteRoute._addFileChildren(
  VocabularyRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VocabularyRouteRoute: VocabularyRouteRouteWithChildren,
  DictationRoute: DictationRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
